### PR TITLE
#267 BatchService timezone hiba - fix

### LINKED ISSUE #267: BatchService timezone hiba
A `BatchService` jelenleg nem veszi figyelembe az időzónát amit a persistence.xml-ben beállítunk (`hibernate.jdbc.time_zone`), így az x__insdate-hez minden update-nél hozzáadódik 1-2 óra. A `BatchService`-nek használnia kellene a beállított értéket `OffsetDateTime` és `LocalDateTime` esetén.

```java
TimeZone dbTimeZone = entityManager.unwrap(Session.class).getSessionFactory().getSessionFactoryOptions().getJdbcTimeZone();
```

### PR DESCRIPTION
**Pull request by martin-nagy**
closes #267

### CODE REVIEW

File: coffee-jpa/src/main/java/hu/icellmobilsoft/coffee/jpa/sql/batch/BatchService.java [hunk 1]
```diff
@@ -567,14 +577,75 @@ protected <E> void setPsObject(PreparedStatement ps, int parameterIndex, Type ty
...
+            } else if (getDbTimezone() != null) {
+                ps.setObject(parameterIndex,
+                        ((LocalDateTime) value).atZone(ZoneId.systemDefault()).withZoneSameInstant(getDbTimezone().toZoneId()).toLocalDateTime(),
+                        TimestampType.INSTANCE.sqlType());
+            } else {
+                ps.setObject(parameterIndex, value, TimestampType.INSTANCE.sqlType());
+            }
+            return true;
+        }
+        if (type instanceof OffsetDateTimeType) {
```
Comment (rombow) [inline coffee-jpa/src/main/java/hu/icellmobilsoft/coffee/jpa/sql/batch/BatchService.java:637]: ZonedDateTime-ra jol fog mukodni?

**Review by rombow — APPROVED** [review]

**Review by rombow — APPROVED** [review]

**Review by petrenyi-mark — DISMISSED** [review]

**Review by czenczl — DISMISSED** [review]

**Review by rombow — APPROVED** [review]

**Review by czenczl — APPROVED** [review]

**Review by petrenyi-mark — APPROVED** [review]
