### PR TITLE
Feature/390 scope fixes

### LINKED ISSUE #390: ExceptionMapper.öknek scope adás
ExceptionMapper megvalósításoknak szükséges legalább egy @Dependent scope ahhoz hogy quarkus 3-ban legyen injectelt példányok.

### PR DESCRIPTION
**Pull request by speter555**
closed #390

### CODE REVIEW

File: coffee-module/coffee-module-mp/coffee-module-mp-restclient/src/main/java/hu/icellmobilsoft/coffee/module/mp/restclient/provider/DefaultBaseExceptionResponseExceptionMapper.java [hunk 1]
```diff
@@ -37,13 +34,17 @@
 import hu.icellmobilsoft.coffee.module.mp.restclient.exception.FaultTypeParser;
 import hu.icellmobilsoft.coffee.tool.gson.JsonUtil;
 import hu.icellmobilsoft.coffee.tool.utils.marshalling.MarshallingUtil;
+import jakarta.enterprise.context.Dependent;
```
Comment (rombow) [inline coffee-module/coffee-module-mp/coffee-module-mp-restclient/src/main/java/hu/icellmobilsoft/coffee/module/mp/restclient/provider/DefaultBaseExceptionResponseExceptionMapper.java:37]: import ordert leccives alicsd be

**Review by rombow — APPROVED** [review]

File: coffee-module/coffee-module-mp/coffee-module-mp-restclient/src/main/java/hu/icellmobilsoft/coffee/module/mp/restclient/provider/DefaultBaseExceptionResponseExceptionMapper.java (hunk 1 above)
Comment (speter555) [reply coffee-module/coffee-module-mp/coffee-module-mp-restclient/src/main/java/hu/icellmobilsoft/coffee/module/mp/restclient/provider/DefaultBaseExceptionResponseExceptionMapper.java]: javítotam

**Review by rombow — APPROVED** [review]

**Review by czenczl — APPROVED** [review]

**Review by vasizs — APPROVED** [review]

**Review by bucherarnold — APPROVED** [review]
